strategy:
  - name: My default processing strategy
    type: ParallelProcessing
    options:
      MaxThreads: 10
      ProcessorThroughput: 2
      OnProcessingError: warning
      Queue: TailQueue
      Processor: Shell

queue:
  - name: DummyQueue
    type: Dummy
    options:
      RandomSleepDelay: 10

  - name: TailQueue
    type: Tail
    options:
      Path: /data/playground/qp/config/dummy.yaml

  - name: TailQueueFIFO
    type: Tail
    options:
      Path: /tmp/1

  - name: Sqs
    type: Sqs
    options:
      QueueName: "print-queue-dead-letter-dev"
      AwsRegion: eu-west-1
      AwsProfile: printingservice
      WaitTimeSeconds: 20

processor:
  - name: Stdout
    type: Stdout

  - name: Shell
    type: Shell
    options:
      MessagePlaceholder: "%msg%"
      Command: "echo %msg% | grep 34"
      EchoOutput: false

  - name: HttpProxy
    type: HttpProxy
    options:
      Timeout: 5
      Url: "http://localhost:9000/"