strategy:
  - name: My default processing strategy
    type: ParallelProcessing
    options:
      MaxThreads: 1
      Queue: TailQueueFIFO
      Processor: HttpProxy

queue:
  - name: DummyQueue
    type: Dummy
    options:
      RandomSleepDelay: 1000
  - name: TailQueue
    type: Tail
    options:
      Path: /data/playground/qp/config/dummy.yaml
  - name: TailQueueFIFO
    type: Tail
    options:
      Path: /tmp/1

processor:
  - name: Stdout processor
    type: Stdout
  - name: HttpProxy
    type: HttpProxy
    options:
      Timeout: 5
      Url: "http://localhost:9000/"