strategy:
  - name: My default processing strategy
    type: ParallelProcessing
    options:
      MaxThreads: 10
      Queue: DummyQueue
      Processor: Shell

queue:
  - name: DummyQueue
    type: Dummy
    options:
      RandomSleepDelay: 1000

  - name: TailQueue
    type: Tail
    options:
      Path: /data/playground/qp/config/dummy.yaml

  - name: TailQueueFIFO
    type: Tail
    options:
      Path: /tmp/1

  - name: Sqs
    type: Sqs
    options:
      QueueName: "print-queue-dead-letter-dev"
      AwsRegion: eu-west-1
      AwsProfile: printingservice
      WaitTimeSeconds: 20

processor:
  - name: Stdout
    type: Stdout

  - name: Shell
    type: Shell
    options:
      Command: echo
      EchoOutput: true

  - name: HttpProxy
    type: HttpProxy
    options:
      Timeout: 5
      Url: "http://localhost:9000/"